// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-xMth3lKSAbXdTcjK32L6J7IfBt-L8w',
    appId: '1:450265420670:web:3fc6166b5886e289b7992f',
    messagingSenderId: '450265420670',
    projectId: 'flutterproject1-80339',
    authDomain: 'flutterproject1-80339.firebaseapp.com',
    storageBucket: 'flutterproject1-80339.firebasestorage.app',
    measurementId: 'G-JJDY97GEXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzGoto5RaxvwK-KIqEgskHxD0slOx5iqg',
    appId: '1:450265420670:android:b735d09368b69a27b7992f',
    messagingSenderId: '450265420670',
    projectId: 'flutterproject1-80339',
    storageBucket: 'flutterproject1-80339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCorRBewsVgP0CjGL6LvOI9io9htZ0kug',
    appId: '1:450265420670:ios:2238f971439e928cb7992f',
    messagingSenderId: '450265420670',
    projectId: 'flutterproject1-80339',
    storageBucket: 'flutterproject1-80339.firebasestorage.app',
    androidClientId: '450265420670-nsa8ece9vvpkab82puku45fdebjkd9sn.apps.googleusercontent.com',
    iosClientId: '450265420670-ntgf724c795hu8dv92b3q03er67qskib.apps.googleusercontent.com',
    iosBundleId: 'com.ecommerce.app.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCorRBewsVgP0CjGL6LvOI9io9htZ0kug',
    appId: '1:450265420670:ios:2238f971439e928cb7992f',
    messagingSenderId: '450265420670',
    projectId: 'flutterproject1-80339',
    storageBucket: 'flutterproject1-80339.firebasestorage.app',
    androidClientId: '450265420670-nsa8ece9vvpkab82puku45fdebjkd9sn.apps.googleusercontent.com',
    iosClientId: '450265420670-ntgf724c795hu8dv92b3q03er67qskib.apps.googleusercontent.com',
    iosBundleId: 'com.ecommerce.app.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9-xMth3lKSAbXdTcjK32L6J7IfBt-L8w',
    appId: '1:450265420670:web:b8c8a8af85a32ef7b7992f',
    messagingSenderId: '450265420670',
    projectId: 'flutterproject1-80339',
    authDomain: 'flutterproject1-80339.firebaseapp.com',
    storageBucket: 'flutterproject1-80339.firebasestorage.app',
    measurementId: 'G-HTLRHTVL4W',
  );
}
